### ISSUE TITLE
[Sortable list] create component

### ISSUE THREAD

**Issue by mattgoud** [PrestaShopCorp/puik#364]
## Description
- Figma:  https://www.figma.com/design/YxI7gWKwOKc0QGMvaTal8j/PrestaShop-Core-Design-Kit?node-id=19569-2110&t=5F2VdhzzuEgeI2wv-0
- Zeroheight: https://docs.uikit.prestashop.com/34f250d18/p/882b4b-sortable-list

## Tasks
- [x] - create Vue  component
- [x] - add story (Storybook)
 - [x] - add tests (Vitest)
